// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAzlKUf0e6F8pApsPD-wjD7XqwuGK8Kps',
    appId: '1:740699909798:android:2b0003b0eead0ee3690e67',
    messagingSenderId: '740699909798',
    projectId: 'talkbase-d0b3c',
    storageBucket: 'talkbase-d0b3c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbqlwUi40Nd9s13GQrCbOg3gZjGhfRu_0',
    appId: '1:740699909798:ios:8eb66642117abb58690e67',
    messagingSenderId: '740699909798',
    projectId: 'talkbase-d0b3c',
    storageBucket: 'talkbase-d0b3c.firebasestorage.app',
    iosBundleId: 'com.viheer.talkbase',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaE3GgHDpw3AYAjMMQ6KZYx4skNJCKdZQ',
    appId: '1:740699909798:web:cbf8a3c9e4d02bfd690e67',
    messagingSenderId: '740699909798',
    projectId: 'talkbase-d0b3c',
    authDomain: 'talkbase-d0b3c.firebaseapp.com',
    storageBucket: 'talkbase-d0b3c.firebasestorage.app',
    measurementId: 'G-JTWDMVYXBY',
  );

}